project:
  type: default
  output-dir: reports

format:
  gfm:
    toc: true
    toc-depth: 1
    filters:
      - assets/fold-code.lua   # code folding, which quarto only does for HTML
  pptx:
    slide-level: 2
    echo: false
    reference-doc: assets/ouhsc_ppt_template.pptx
